[workspace]
resolver = "3"
members = ["app", "bootloader", "crates/*", "tools/*"]
default-members = ["app"]

[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace.dependencies]

# Embedded
embassy-stm32 = { version = "0.6.0", features = [ "defmt", "time", "time-driver-any", "stm32h723vg", "unstable-pac", "exti"]  }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-1_000_000"] }
embassy-futures = { version = "0.1.2" }

embassy-boot-stm32 = { version = "0.8.0", features = ["defmt"] }

cortex-m = { version = "0.7.9", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.6"

defmt = "1.1"

# Common
blake3 = { version = "=1.8.0", default-features = false, features = ["traits-preview", "digest"] }

serde = { version = "1.0.229", default-features = false, features = ["alloc", "derive"] }
minicbor-serde = { version = "0.7.1", features = ["alloc"] }

# Tools
tokio = { version = "1.53.1", features = [ "rt-multi-thread", "io-util", "macros", "time", "net" ] }
clap = { version = "4.6.6", features = ["derive"] }
anyhow = "1.0.104"

[profile.dev]
opt-level = 3
debug = 2
debug-assertions = false
lto = true
codegen-units = 16

[profile.release]
lto = true
debug = 2
